[tool.poetry]
name = "frontegg"
version = "4.0.0"
description = "Frontegg is a web platform where SaaS companies can set up their fully managed, scalable and brand aware - SaaS features and integrate them into their SaaS portals in up to 5 lines of code."
homepage = "https://frontegg.com/"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Operating System :: OS Independent"
]
authors = ["Frontegg LTD <hello@frontegg.com>"]
readme = "README-PYPI.rst"

[tool.poetry.dependencies]
python = "^3.10"
flask = { version = "^3.1.3", optional = true }
fastapi = { version = "*", optional = true }
requests = "^2.33.0"
arrow = "^1.2.3"
aiohttp = {version = "^3.14.1", optional = true}
PyJWT = "^2.10.1"
cryptography = ">=44.0.1"
typing-extensions = "^4.4.0"
httpx = ">=0.26.0"

[tool.poetry.extras]
flask = ["flask"]
fastapi = ["fastapi"]

[tool.poetry.dev-dependencies]
pytest = "^9.0.3"
pytest-flask = "^1.3.0"
pytest-vcr = "^1.0.2"
flake8 = "^7.1.0"
autopep8 = "^2.3.0"
pydocstyle = "^6.3.0"

[tool.poetry.group.dev.dependencies]
flask-cors = "^6.0.0"
uvicorn = "^0.34.0"
fakeredis = "^2.20.0"


[tool.poetry.group.extras.dependencies]
redis = "^4.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
